### ISSUE TITLE
SWC Core 版本需要升级， 否则会造成不兼容问题。验证了一下 @swc/core最高可用到：1.3.105； 在此之后的版本都会出现以下错误。

### ISSUE THREAD

**Issue by BigFaceMaster** [umijs/swc-plugin-auto-css-modules#1]
![CleanShot 2024-02-20 at 18 37 42@2x](https://github.com/umijs/swc-plugin-auto-css-modules/assets/15710933/850d60ff-b5a1-48ad-ad9a-6c878eddd071)

**Comment by fz6m** [comment]
发布了 `v1.6.0` ，可适用于 swc core >= `1.4.0` 。

我佛了，swc 变化的太快插件天天 breaking change 啊。
